# 개발 환경 설정
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    com.team5_jsb: DEBUG