# 개발 환경 설정
spring:
  config:
    import: "optional:sm://"

  cloud:
    gcp:
      secretmanager:
        project-id: complete-welder-330305

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: '${sm\://google-oauth-client-id}'
            client-secret: '${sm\://google-oauth-client-secret}'
            scope: openid, email, profile
            redirect-uri: "{baseUrl}/login/oauth2/code/google"

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.cloud.gcp.secretmanager: DEBUG
    com.team5_jsb: DEBUG